baseURL = "https://swlacy.com"
languageCode = "en-us"
title = "Sid's Blog"

theme = "hugo-port-theme"

[params]
    author = "Sid Lacy"
    headshot = "/headshot.png"
    license = "MIT License"
    licenseLink = "https://opensource.org/licenses/MIT"
    attributionPage = "/attribution"
    authorPage = "/about"
    repoLink = "https://github.com/lacysw/blog"
    logoPath = "/logo.png"
    showLastBuilt = true
    showCommitHash = true
    email = "contact@swlacy.com"
    tagline = "I ramble about security and technology."
    footnote = "Hey there! Thanks for taking the time to read this post. Notice something in need of improvement? Please, do not hesitate to let me know via email or a git PR. Kind regards."

[menu]
  [[menu.socials]]
    name = "Email"
    pre = "mail"
    url = "mailto:contact@swlacy.com?subject=Hello!"
    weight = 1
  [[menu.socials]]
    name = "Twitter"
    pre = "twitter"
    url = "https://twitter.com/actuallysid"
    weight = 2
  [[menu.socials]]
    name = "LinkedIn"
    pre = "linkedin"
    url = "https://linkedin.com/in/lacysw"
    weight = 3
  [[menu.socials]]
    name = "GitHub"
    pre = "github"
    url = "https://github.com/lacysw"
    weight = 4
  [[menu.socials]]
    name = "More"
    pre = "link"
    url = "/about#socials"
    weight = 5

enableGitInfo = true
pygmentsOptions = "linenos=inline"

[markup]
  [markup.highlight]
    style = 'lovelace'
    tabWidth = 4

[frontmatter]
    date = ["date", "publishDate", "lastmod"]
    lastmod = ["lastmod", ":git", "date", "publishDate"]
